name: Run tests

on:  
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'    # every day at midnight

jobs:  
  test:
    runs-on: ubuntu-latest

    # Comments in YAML start with a # (hashtag symbol)
    # Comment your thoughts for yourself or coworkers :)
    steps:
    - name: trial
